Alias /media/ /data/sifter/media/
Alias /static/ /data/sifter/static/
Alias /downloads/ /data/sifter/output/

<Directory /data/sifter/static/>
    Require all granted
</Directory>

<Directory /data/sifter/media/>
    Require all granted
</Directory>

<Directory /data/sifter/output/>
    Require all granted
</Directory>

<VirtualHost *:80>
    ServerName sifter.berkeley.edu

    ProxyPreserveHost On
    ProxyPass /static/ !
    ProxyPass /media/ !
    ProxyPass /downloads/ !
    ProxyPass / http://127.0.0.1:8000/
    ProxyPassReverse / http://127.0.0.1:8000/

    ErrorLog ${APACHE_LOG_DIR}/sifter-error.log
    CustomLog ${APACHE_LOG_DIR}/sifter-access.log combined
</VirtualHost>

<VirtualHost *:443>
    ServerName sifter.berkeley.edu

    SSLEngine on
    SSLCertificateFile /etc/ssl/certs/sifter_berkeley_edu_cert.cer
    SSLCertificateKeyFile /etc/ssl/private/sifter.berkeley.edu.key
    SSLCertificateChainFile /etc/ssl/certs/sifter_berkeley_edu_interm.cer

    ProxyPreserveHost On
    ProxyPass /static/ !
    ProxyPass /media/ !
    ProxyPass /downloads/ !
    ProxyPass / http://127.0.0.1:8000/
    ProxyPassReverse / http://127.0.0.1:8000/

    ErrorLog ${APACHE_LOG_DIR}/sifter-ssl-error.log
    CustomLog ${APACHE_LOG_DIR}/sifter-ssl-access.log combined
</VirtualHost>
